name: Update README

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: |
          npm install -g @octokit/rest
        continue-on-error: false

      - name: Update README
        id: update-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get current date and time
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S")

          # Check if README.md exists
          if [ ! -f README.md ]; then
            echo "::error::README.md file not found"
            exit 1
          fi

          # Update the README with the current date
          if ! sed -i "s/Last%20Updated-.*-2E8BC0/Last%20Updated-$CURRENT_DATE-2E8BC0/" README.md; then
            echo "::error::Failed to update README.md"
            exit 1
          fi

          # Check if the README was updated
          if git diff --quiet README.md; then
            echo "::notice::No changes detected in README.md"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::Changes detected in README.md"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.update-readme.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README with latest stats
          branch: update-readme
          delete-branch: true
          title: Update README
          body: Automated update of README with latest stats.
          labels: automated-pr
